# Generated by Django 6.1.1 on 2026-10-05 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('instrucciones', models.TextField(blank=True)),
                ('equipo', models.CharField(blank=True, max_length=100)),
                ('dificultad', models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='BASICO', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ejercicios/')),
                ('video', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('es_predefinida', models.BooleanField(default=False)),
                ('duracion_semanas', models.PositiveIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_creadas', to='usuarios.usuario')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas', to='clientes.objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_asignadas', to='clientes.cliente')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='entrenamientos.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='RutinaEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticiones', models.PositiveIntegerField(default=10)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('descanso_segundos', models.PositiveIntegerField(default=60)),
                ('intensidad', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='entrenamientos.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='entrenamientos.rutina')),
            ],
        ),
    ]
