# Generated by Django 6.1.1 on 2026-10-05 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unidad', models.CharField(max_length=30)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='nutricion.alimento')),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='nutricion.comidadieta')),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietas_creadas', to='usuarios.usuario')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietas', to='clientes.objetivo')),
            ],
        ),
        migrations.AddField(
            model_name='comidadieta',
            name='dieta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='nutricion.dieta'),
        ),
        migrations.CreateModel(
            name='AsignacionDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas_asignadas', to='clientes.cliente')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='nutricion.dieta')),
            ],
        ),
    ]
